baseURL = "https://lavara123.github.io"
languageCode = "tr-TR"
title = "İbrahim Boyacı"
disqusShortname = 'lavara123'
# if true, auto-detect Chinese/Japanese/Korean Languages in the content. (.Summary and .WordCount can work properly in CJKLanguage)
hasCJKLanguage = true

# DO　NOT MODIFY THIS CONFIG（不要修改这个配置）
publishDir = "docs"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[Params]
  author = "İbrahim Boyacı"
  subtitle = "Büyük beyinler fikirleri, orta beyinler olayları, küçük beyinler kişileri konuşur."
  copyright = "Copyleft@Kevin Tan"
  logo = "/img/profile.jpg"
  profile_bg = "/img/profile-bg.jpg"

# 主菜单
[[menu.main]]
    name = "Anasayfa"
    weight = 1
    pre = "<i class='material-icons'>home</i>"
    url = "/"

[[menu.main]]
    name = "Arşiv"
    weight = 2
    pre = "<i class='material-icons'>archive</i>"
    url = "/archive/"

[[menu.main]]
    name = "Hakkında"
    weight = 3
    pre = "<i class='material-icons'>person</i>"
    url = "/about/"

#  友情链接
[[menu.friend]]
  name = "Frantic1048"
  url = "https://frantic1048.logdown.com/"

[[menu.friend]]
  name = "HclMaster"
  url = "https://hclmaster.github.io/"

[[menu.friend]]
  name = "WANG Hsü-Tung"
  url = "https://whst.github.io/"


# 社交账号
[[menu.social]]
  pre = "<svg class='svg-icons svg-icons-github'><use xlink:href='#svg-icons-github'></use></svg>"
  name = "Github"
  identifier = "@lavara123"
  url = "https://github.com/lavara123"

[[menu.social]]
  pre = "<svg class='svg-icons svg-icons-facebook'><use xlink:href='#svg-icons-facebook'></use></svg>"
  name = "Facebook"
  identifier = "/lavara123"
  url = "https://www.facebook.com/lavara123"

[[menu.social]]
  pre = "<svg class='svg-icons svg-icons-google-plus3'><use xlink:href='#svg-icons-google-plus3'></use></svg>"
  name = "Google+"
  identifier = "İbrahim Boyacı"
  url = "https://plus.google.com/u/0/110651418479071272516"


# 文章归类类目
[[menu.taxonomy]]
  pre = "<i class='material-icons'>local_offer</i>"
  name = "Etiketler"
  identifier="tags"

[[menu.taxonomy]]
  pre = "<i class='material-icons'>class</i>"
  name = "Katagoriler"
  identifier="categories"

